/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RolesRoleRouteImport } from './routes/roles.$role'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as GuidesCreativeDirectorPortfolioRouteImport } from './routes/guides.creative-director-portfolio'
import { Route as ClientsClientRouteImport } from './routes/clients.$client'
import { Route as CategoriesCategoryRouteImport } from './routes/categories.$category'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoleRoute = RolesRoleRouteImport.update({
  id: '/roles/$role',
  path: '/roles/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesCreativeDirectorPortfolioRoute =
  GuidesCreativeDirectorPortfolioRouteImport.update({
    id: '/guides/creative-director-portfolio',
    path: '/guides/creative-director-portfolio',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientsClientRoute = ClientsClientRouteImport.update({
  id: '/clients/$client',
  path: '/clients/$client',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryRoute = CategoriesCategoryRouteImport.update({
  id: '/categories/$category',
  path: '/categories/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/clients/$client': typeof ClientsClientRoute
  '/guides/creative-director-portfolio': typeof GuidesCreativeDirectorPortfolioRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/roles/$role': typeof RolesRoleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/clients/$client': typeof ClientsClientRoute
  '/guides/creative-director-portfolio': typeof GuidesCreativeDirectorPortfolioRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/roles/$role': typeof RolesRoleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/clients/$client': typeof ClientsClientRoute
  '/guides/creative-director-portfolio': typeof GuidesCreativeDirectorPortfolioRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/roles/$role': typeof RolesRoleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/categories/$category'
    | '/clients/$client'
    | '/guides/creative-director-portfolio'
    | '/projects/$slug'
    | '/roles/$role'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/categories/$category'
    | '/clients/$client'
    | '/guides/creative-director-portfolio'
    | '/projects/$slug'
    | '/roles/$role'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/categories/$category'
    | '/clients/$client'
    | '/guides/creative-director-portfolio'
    | '/projects/$slug'
    | '/roles/$role'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CategoriesCategoryRoute: typeof CategoriesCategoryRoute
  ClientsClientRoute: typeof ClientsClientRoute
  GuidesCreativeDirectorPortfolioRoute: typeof GuidesCreativeDirectorPortfolioRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  RolesRoleRoute: typeof RolesRoleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/$role': {
      id: '/roles/$role'
      path: '/roles/$role'
      fullPath: '/roles/$role'
      preLoaderRoute: typeof RolesRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/creative-director-portfolio': {
      id: '/guides/creative-director-portfolio'
      path: '/guides/creative-director-portfolio'
      fullPath: '/guides/creative-director-portfolio'
      preLoaderRoute: typeof GuidesCreativeDirectorPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$client': {
      id: '/clients/$client'
      path: '/clients/$client'
      fullPath: '/clients/$client'
      preLoaderRoute: typeof ClientsClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$category': {
      id: '/categories/$category'
      path: '/categories/$category'
      fullPath: '/categories/$category'
      preLoaderRoute: typeof CategoriesCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CategoriesCategoryRoute: CategoriesCategoryRoute,
  ClientsClientRoute: ClientsClientRoute,
  GuidesCreativeDirectorPortfolioRoute: GuidesCreativeDirectorPortfolioRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  RolesRoleRoute: RolesRoleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
